### ISSUE TITLE
Spike: Investigate an extraction layer that can satisfy capablity dependencies

### ISSUE THREAD

**Issue by mikevanhemert** [defenseunicorns/uds-package-software-factory#22]
As a SWF Engineer
I need to know that Virtual Service can mask internal and external resources
So that capability dependencies are really easily satisfiable

Acceptance Criteria
- Solution works with any k8s cluster / distro
- Solution can work with internal and externally deployed things (Zolando & RDS, for example)
- Solution can work with on-prem and cloud infra

**Comment by corang** [comment]
My gut feeling is to use a k8s service with an externalName pointing to the domain name of the dependency or in the case of the dependency not having a domain name then a headless service with the IP of the dependency in the definition of said headless service

**Comment by corang** [comment]
Actually headless all the time for consistency is probably better

**Comment by corang** [comment]
So here's what I came up with.

When a dependency has a domain name that is discoverable from the cluster:
```
apiVersion: v1
kind: Service
metadata:
  name: some-dep
spec:
  type: ExternalName
  externalName: google.com
```

When a dependency doesn't have a domain name or it isn't discoverable from the cluster (must have a static ip)
```
apiVersion: v1
kind: Service
metadata:
  name: some-dep
spec:
  clusterIP: None
---
apiVersion: v1
kind: Endpoints
metadata:
  name: some-dep
subsets:
  - addresses:
      - ip: 8.8.8.8
```

The `ExternalName` based service can point to another service in the cluster even if it's in a different namespace by using the FQDN of the service name. `cluster.local` must match the domain name of the cluster.
```
apiVersion: v1
kind: Service
metadata:
  name: some-dep-internal
spec:
  type: ExternalName
  externalName: dep-fulfillment.otherns.svc.cluster.local
```
